{ identifier: 'name',label: 'label',items: [

{name:'Dojox', label:'Dojox', hasDesc:true,hasLinks:true,type:'folder',baseUrl:'Dojox/Dojox.',children:[{_reference:'JGTDSL_DashBoard'},{_reference:'Dojox_Charting'},{_reference:'Dojox_DTL'},{_reference:'JGTDSL_MD'},{_reference:'Dojox_Gfx3D'},{_reference:'Dojox_Grid'},{_reference:'Dojox_Image'},{_reference:'Dojox_Layout'},{_reference:'Dojox_Widgets'}]},
{name:'JGTDSL_DashBoard', label:'Dashboard', hasDesc:true,hasHtml:true,hasLinks:true,baseUrl:'dashBoardContent',centerCaption:'User DashBoard'},
{name:'Dojox_Charting', label:'Charting', hasDesc:true,hasLinks:true,baseUrl:'newPage.php',children:[{_reference:'Dojox_Charting_2D'},{_reference:'Dojox_Charting_Bar'}]},
{name:'Dojox_Charting_2D', label:'2D',children:[{_reference:'Dojox_Charting_2D_Areas,%20No%20Axes,%20Custom%20Strokes%20And%20Fills'},{_reference:'Dojox_Charting_2D_Areas,%20Orange%20theme,%20No%20Axes'},{_reference:'Dojox_Charting_2D_Lines,%20Markers,%20No%20Axes,%20Purple%20Theme,%20Custom%20Min%20Max'},{_reference:'Dojox_Charting_2D_Lines,%20No%20Axes'},{_reference:'Dojox_Charting_2D_Lines,%20No%20Axes,%20Custom%20Strokes'},{_reference:'Dojox_Charting_2D_Updating'}]},
{name:'Dojox_Charting_2D_Areas,%20No%20Axes,%20Custom%20Strokes%20And%20Fills', label:'Areas, No Axes, Custom Strokes And Fills', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Charting/2D/Areas,%20No%20Axes,%20Custom%20Strokes%20And%20Fills/Areas,%20No%20Axes,%20Custom%20Strokes%20And%20Fills.'},
{name:'Dojox_Charting_2D_Areas,%20Orange%20theme,%20No%20Axes', label:'Areas, Orange theme, No Axes', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Charting/2D/Areas,%20Orange%20theme,%20No%20Axes/Areas,%20Orange%20theme,%20No%20Axes.'},
{name:'Dojox_Charting_2D_Lines,%20Markers,%20No%20Axes,%20Purple%20Theme,%20Custom%20Min%20Max', label:'Lines, Markers, No Axes, Purple Theme, Custom Min Max', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Charting/2D/Lines,%20Markers,%20No%20Axes,%20Purple%20Theme,%20Custom%20Min%20Max/Lines,%20Markers,%20No%20Axes,%20Purple%20Theme,%20Custom%20Min%20Max.'},
{name:'Dojox_Charting_2D_Lines,%20No%20Axes', label:'Lines, No Axes', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Charting/2D/Lines,%20No%20Axes/Lines,%20No%20Axes.'},
{name:'Dojox_Charting_2D_Lines,%20No%20Axes,%20Custom%20Strokes', label:'Lines, No Axes, Custom Strokes', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Charting/2D/Lines,%20No%20Axes,%20Custom%20Strokes/Lines,%20No%20Axes,%20Custom%20Strokes.'},
{name:'Dojox_Charting_2D_Updating', label:'Updating', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Charting/2D/Updating/Updating.'},
{name:'Dojox_Charting_Bar', label:'Bar', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Charting/Bar/Bar.'},
{name:'Dojox_DTL', label:'DTL', hasDesc:true,hasLinks:true,baseUrl:'Dojox/DTL/DTL.',children:[{_reference:'Dojox_DTL_Basic%20Template'},{_reference:'Dojox_DTL_Node%20List'}]},
{name:'Dojox_DTL_Basic%20Template', label:'Basic Template', hasDesc:true,baseUrl:'Dojox/DTL/Basic%20Template/Basic%20Template.',children:[{_reference:'Dojox_DTL_Basic%20Template_Local'},{_reference:'Dojox_DTL_Basic%20Template_Remote'}]},
{name:'Dojox_DTL_Basic%20Template_Local', label:'Local', hasDesc:true,hasHtml:true,baseUrl:'Dojox/DTL/Basic%20Template/Local/Local.'},
{name:'Dojox_DTL_Basic%20Template_Remote', label:'Remote', hasDesc:true,hasHtml:true,baseUrl:'Dojox/DTL/Basic%20Template/Remote/Remote.'},
{name:'Dojox_DTL_Node%20List', label:'Node List', hasDesc:true,hasLinks:true,baseUrl:'Dojox/DTL/Node%20List/Node%20List.',children:[{_reference:'Dojox_DTL_Node%20List_Local%20Template'},{_reference:'Dojox_DTL_Node%20List_Remote%20Template'}]},
{name:'Dojox_DTL_Node%20List_Local%20Template', label:'Local Template', hasDesc:true,hasHtml:true,baseUrl:'Dojox/DTL/Node%20List/Local%20Template/Local%20Template.'},
{name:'Dojox_DTL_Node%20List_Remote%20Template', label:'Remote Template', hasDesc:true,hasHtml:true,baseUrl:'Dojox/DTL/Node%20List/Remote%20Template/Remote%20Template.'},
{name:'JGTDSL_MD', label:'Master Data',hasLinks:true,children:[{_reference:'JGTDSL_MD_User%20Information'},{_reference:'JGTDSL_MD_Region/Area%20Information'},{_reference:'JGTDSL_MD_Category%20Information'},{_reference:'JGTDSL_MD_Tariff'},{_reference:'JGTDSL_MD_Bank%20Information'},{_reference:'JGTDSL_MD_Branch%20Information'},{_reference:'JGTDSL_MD_Bank%20Account'},{_reference:'JGTDSL_MD_Meter%20Type'}]},
{name:'JGTDSL_MD_User%20Information', label:'User Information', hasDesc:true,hasHtml:true,baseUrl:'getUserList.action',centerCaption:'User Information'},
{name:'JGTDSL_MD_Region/Area%20Information', label:'Region/Area Information', hasDesc:true,hasHtml:true,baseUrl:'getAreaList.action'},
{name:'JGTDSL_MD_Category%20Information', label:'Category Information', hasDesc:true,hasHtml:true,baseUrl:'getCustomerCategoryList.action'},
{name:'JGTDSL_MD_Tariff', label:'Tariff/Rate', hasDesc:true,hasHtml:true,baseUrl:'getTariffList'},
{name:'JGTDSL_MD_Bank%20Information', label:'Bank Infomration', hasDesc:true,hasHtml:true,baseUrl:'getBankList.action'},
{name:'JGTDSL_MD_Branch%20Information', label:'Branch Infomration', hasDesc:true,hasHtml:true,baseUrl:'getBranchList.action'},
{name:'JGTDSL_MD_Bank%20Account', label:'Account Infomration', hasDesc:true,hasHtml:true,baseUrl:'getAccountList.action'},
{name:'JGTDSL_MD_Meter%20Type', label:'Meter Type', hasDesc:true,hasHtml:true,baseUrl:'getMeterTypeList.action'},
{name:'Dojox_Gfx3D', label:'Gfx3D', hasDesc:true,hasLinks:true,baseUrl:'Dojox/Gfx3D/Gfx3D.',children:[{_reference:'Dojox_Gfx3D_Cube'},{_reference:'Dojox_Gfx3D_Rotate'}]},
{name:'Dojox_Gfx3D_Cube', label:'Cube', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Gfx3D/Cube/Cube.'},
{name:'Dojox_Gfx3D_Rotate', label:'Rotate', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Gfx3D/Rotate/Rotate.'},
{name:'Dojox_Grid', label:'Grid',hasLinks:true,baseUrl:'Dojox/Grid/Grid.',children:[{_reference:'Dojox_Grid_Basic'},{_reference:'Dojox_Grid_Edit%20Dijit'},{_reference:'Dojox_Grid_Styling'},{_reference:'Dojox_Grid_Sub%20Grid'}]},
{name:'Dojox_Grid_Basic', label:'Basic', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Grid/Basic/Basic.'},
{name:'Dojox_Grid_Edit%20Dijit', label:'Edit Dijit', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Grid/Edit%20Dijit/Edit%20Dijit.'},
{name:'Dojox_Grid_Styling', label:'Styling', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Grid/Styling/Styling.'},
{name:'Dojox_Grid_Sub%20Grid', label:'Sub Grid', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Grid/Sub%20Grid/Sub%20Grid.'},
{name:'Dojox_Image', label:'Image', hasDesc:true,hasLinks:true,baseUrl:'Dojox/Image/Image.',children:[{_reference:'Dojox_Image_Gallery'},{_reference:'Dojox_Image_Lightbox'},{_reference:'Dojox_Image_SlideShow'},{_reference:'Dojox_Image_ThumbnailPicker'}]},
{name:'Dojox_Image_Gallery', label:'Gallery',hasLinks:true,baseUrl:'Dojox/Image/Gallery/Gallery.',children:[{_reference:'Dojox_Image_Gallery_Default'},{_reference:'Dojox_Image_Gallery_Custom%20Size'},{_reference:'Dojox_Image_Gallery_Flickr%20DataStore'},{_reference:'Dojox_Image_Gallery_Picasa%20DataStore'}]},
{name:'Dojox_Image_Gallery_Default', label:'Default', hasDesc:true,hasHtml:true,hasJs:true,baseUrl:'Dojox/Image/Gallery/Default/Default.'},
{name:'Dojox_Image_Gallery_Custom%20Size', label:'Custom Size', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Image/Gallery/Custom%20Size/Custom%20Size.'},
{name:'Dojox_Image_Gallery_Flickr%20DataStore', label:'Flickr DataStore', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Image/Gallery/Flickr%20DataStore/Flickr%20DataStore.'},
{name:'Dojox_Image_Gallery_Picasa%20DataStore', label:'Picasa DataStore', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Image/Gallery/Picasa%20DataStore/Picasa%20DataStore.'},
{name:'Dojox_Image_Lightbox', label:'Lightbox',hasLinks:true,baseUrl:'Dojox/Image/Lightbox/Lightbox.',children:[{_reference:'Dojox_Image_Lightbox_Single'},{_reference:'Dojox_Image_Lightbox_Grouped'},{_reference:'Dojox_Image_Lightbox_Flickr%20Group'}]},
{name:'Dojox_Image_Lightbox_Single', label:'Single', hasDesc:true,hasHtml:true,hasJs:true,baseUrl:'Dojox/Image/Lightbox/Single/Single.'},
{name:'Dojox_Image_Lightbox_Grouped', label:'Grouped', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Image/Lightbox/Grouped/Grouped.'},
{name:'Dojox_Image_Lightbox_Flickr%20Group', label:'Flickr Group', hasDesc:true,hasHtml:true,hasJs:true,baseUrl:'Dojox/Image/Lightbox/Flickr%20Group/Flickr%20Group.'},
{name:'Dojox_Image_SlideShow', label:'SlideShow',hasLinks:true,baseUrl:'Dojox/Image/SlideShow/SlideShow.',children:[{_reference:'Dojox_Image_SlideShow_Basic'},{_reference:'Dojox_Image_SlideShow_Customized'}]},
{name:'Dojox_Image_SlideShow_Basic', label:'Basic', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Image/SlideShow/Basic/Basic.'},
{name:'Dojox_Image_SlideShow_Customized', label:'Customized', hasDesc:true,hasHtml:true,hasJs:true,baseUrl:'Dojox/Image/SlideShow/Customized/Customized.'},
{name:'Dojox_Image_ThumbnailPicker', label:'ThumbnailPicker',hasLinks:true,baseUrl:'Dojox/Image/ThumbnailPicker/ThumbnailPicker.',children:[{_reference:'Dojox_Image_ThumbnailPicker_Default'},{_reference:'Dojox_Image_ThumbnailPicker_Customized%201'},{_reference:'Dojox_Image_ThumbnailPicker_Vertical'}]},
{name:'Dojox_Image_ThumbnailPicker_Default', label:'Default', hasDesc:true,hasHtml:true,hasJs:true,baseUrl:'Dojox/Image/ThumbnailPicker/Default/Default.'},
{name:'Dojox_Image_ThumbnailPicker_Customized%201', label:'Customized 1', hasDesc:true,hasHtml:true,hasJs:true,baseUrl:'Dojox/Image/ThumbnailPicker/Customized%201/Customized%201.'},
{name:'Dojox_Image_ThumbnailPicker_Vertical', label:'Vertical', hasDesc:true,hasHtml:true,hasJs:true,baseUrl:'Dojox/Image/ThumbnailPicker/Vertical/Vertical.'},
{name:'Dojox_Layout', label:'Layout',hasLinks:true,baseUrl:'Dojox/Layout/Layout.',children:[{_reference:'Dojox_Layout_RadioGroup'},{_reference:'Dojox_Layout_Resize%20Handle'}]},
{name:'Dojox_Layout_RadioGroup', label:'RadioGroup',hasLinks:true,baseUrl:'Dojox/Layout/RadioGroup/RadioGroup.',children:[{_reference:'Dojox_Layout_RadioGroup_Basic'},{_reference:'Dojox_Layout_RadioGroup_Fade'},{_reference:'Dojox_Layout_RadioGroup_Slide'}]},
{name:'Dojox_Layout_RadioGroup_Basic', label:'Basic', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Layout/RadioGroup/Basic/Basic.'},
{name:'Dojox_Layout_RadioGroup_Fade', label:'Fade', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Layout/RadioGroup/Fade/Fade.'},
{name:'Dojox_Layout_RadioGroup_Slide', label:'Slide', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Layout/RadioGroup/Slide/Slide.'},
{name:'Dojox_Layout_Resize%20Handle', label:'Resize Handle',hasLinks:true,baseUrl:'Dojox/Layout/Resize%20Handle/Resize%20Handle.',children:[{_reference:'Dojox_Layout_Resize%20Handle_Animated'},{_reference:'Dojox_Layout_Resize%20Handle_Basic'},{_reference:'Dojox_Layout_Resize%20Handle_X%20Axis'},{_reference:'Dojox_Layout_Resize%20Handle_Y%20Axis'}]},
{name:'Dojox_Layout_Resize%20Handle_Animated', label:'Animated',hasHtml:true,baseUrl:'Dojox/Layout/Resize%20Handle/Animated/Animated.'},
{name:'Dojox_Layout_Resize%20Handle_Basic', label:'Basic', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Layout/Resize%20Handle/Basic/Basic.'},
{name:'Dojox_Layout_Resize%20Handle_X%20Axis', label:'X Axis', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Layout/Resize%20Handle/X%20Axis/X%20Axis.'},
{name:'Dojox_Layout_Resize%20Handle_Y%20Axis', label:'Y Axis', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Layout/Resize%20Handle/Y%20Axis/Y%20Axis.'},
{name:'Dojox_Widgets', label:'Widgets', hasDesc:true,hasLinks:true,baseUrl:'Dojox/Widgets/Widgets.',children:[{_reference:'Dojox_Widgets_Color%20Picker'},{_reference:'Dojox_Widgets_FishEyeLite'},{_reference:'Dojox_Widgets_Iterator'},{_reference:'Dojox_Widgets_SortList'},{_reference:'Dojox_Widgets_TimeSpinner'},{_reference:'Dojox_Widgets_Toaster'}]},
{name:'Dojox_Widgets_Color%20Picker', label:'Color Picker',hasLinks:true,baseUrl:'Dojox/Widgets/Color%20Picker/Color%20Picker.',children:[{_reference:'Dojox_Widgets_Color%20Picker_Basic'},{_reference:'Dojox_Widgets_Color%20Picker_Customized'}]},
{name:'Dojox_Widgets_Color%20Picker_Basic', label:'Basic', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/Color%20Picker/Basic/Basic.'},
{name:'Dojox_Widgets_Color%20Picker_Customized', label:'Customized', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/Color%20Picker/Customized/Customized.'},
{name:'Dojox_Widgets_FishEyeLite', label:'FishEyeLite', hasDesc:true,hasLinks:true,baseUrl:'Dojox/Widgets/FishEyeLite/FishEyeLite.',children:[{_reference:'Dojox_Widgets_FishEyeLite_Anchor%20Tags'},{_reference:'Dojox_Widgets_FishEyeLite_Images'},{_reference:'Dojox_Widgets_FishEyeLite_List%20Elements'},{_reference:'Dojox_Widgets_FishEyeLite_Spans'}]},
{name:'Dojox_Widgets_FishEyeLite_Anchor%20Tags', label:'Anchor Tags', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/FishEyeLite/Anchor%20Tags/Anchor%20Tags.'},
{name:'Dojox_Widgets_FishEyeLite_Images', label:'Images', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/FishEyeLite/Images/Images.'},
{name:'Dojox_Widgets_FishEyeLite_List%20Elements', label:'List Elements', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/FishEyeLite/List%20Elements/List%20Elements.'},
{name:'Dojox_Widgets_FishEyeLite_Spans', label:'Spans', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/FishEyeLite/Spans/Spans.'},
{name:'Dojox_Widgets_Iterator', label:'Iterator', hasDesc:true,hasLinks:true,baseUrl:'Dojox/Widgets/Iterator/Iterator.',children:[{_reference:'Dojox_Widgets_Iterator_Array'},{_reference:'Dojox_Widgets_Iterator_Array%20Property'},{_reference:'Dojox_Widgets_Iterator_Data%20Store'}]},
{name:'Dojox_Widgets_Iterator_Array', label:'Array', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/Iterator/Array/Array.'},
{name:'Dojox_Widgets_Iterator_Array%20Property', label:'Array Property',hasHtml:true,baseUrl:'Dojox/Widgets/Iterator/Array%20Property/Array%20Property.'},
{name:'Dojox_Widgets_Iterator_Data%20Store', label:'Data Store', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/Iterator/Data%20Store/Data%20Store.'},
{name:'Dojox_Widgets_SortList', label:'SortList', hasDesc:true,baseUrl:'Dojox/Widgets/SortList/SortList.',children:[{_reference:'Dojox_Widgets_SortList_From%20Markup'},{_reference:'Dojox_Widgets_SortList_From%20Data%20Store'},{_reference:'Dojox_Widgets_SortList_Custom%20Sort'}]},
{name:'Dojox_Widgets_SortList_From%20Markup', label:'From Markup', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/SortList/From%20Markup/From%20Markup.'},
{name:'Dojox_Widgets_SortList_From%20Data%20Store', label:'From Data Store', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/SortList/From%20Data%20Store/From%20Data%20Store.'},
{name:'Dojox_Widgets_SortList_Custom%20Sort', label:'Custom Sort', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/SortList/Custom%20Sort/Custom%20Sort.'},
{name:'Dojox_Widgets_TimeSpinner', label:'TimeSpinner', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/TimeSpinner/TimeSpinner.'},
{name:'Dojox_Widgets_Toaster', label:'Toaster', hasDesc:true,hasLinks:true,baseUrl:'Dojox/Widgets/Toaster/Toaster.',children:[{_reference:'Dojox_Widgets_Toaster_Basic'},{_reference:'Dojox_Widgets_Toaster_With%20Separator'}]},
{name:'Dojox_Widgets_Toaster_Basic', label:'Basic', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/Toaster/Basic/Basic.'},
{name:'Dojox_Widgets_Toaster_With%20Separator', label:'With Separator', hasDesc:true,hasHtml:true,baseUrl:'Dojox/Widgets/Toaster/With%20Separator/With%20Separator.'}
]}
